### ISSUE TITLE
`react/function-component-definition` weakens our types

### ISSUE THREAD

**Issue by adrianbw** [vercel/style-guide#27]
I know we had a conversation on function definition before, but I'd like to at least surface it briefly. I really think it's making our typings weaker. Consider when creating a default Next app. When you do, you get an index.tsx looks like this:

![Screen Shot 2022-07-18 at 12 38 24 PM](https://user-images.githubusercontent.com/12662580/179570248-8ac02295-0e8a-4ba2-812f-843ea22b42d7.png)

That `NextPage` type is actually _really_ useful. By forcing function declarations, we're stripping away a level of type security. I'd really like to see us change this.

**Comment by dglsparsons** [comment]
What type security _is_ NextPage introducing here that can't be done with a function component? 

I'm unclear on the benefits over a typed `function`, e.g. 
```typescript 
function HomePage(): ReactElement {
```

**Comment by adrianbw** [comment]
Like `React.FC` and similar, it's richer than just returning a React element:

![Screen Shot 2022-07-18 at 2 06 07 PM](https://user-images.githubusercontent.com/12662580/179590029-5a452809-b5f7-44e5-b864-f9d2042617ca.png)

**Comment by dglsparsons** [comment]
I mean, `React.FC` is contentious anyway because of the implicit inclusion of `children`, regardless of whether `children` makes sense for the component. 

It looks like your example returns an `Element` type anyway? 

Looking into it, I think all the `NextPage` does is:
- specify the type of the props (that you have to specify inside the generic), 
- set the return type as `ReactElement` (if you're using a function component)

Also: 
- it allows both `ClassComponents` and `FunctionComponents` (arguably not a good thing),
- it allows `getInitialProps` to be set on the page (arguably should just be exported alongside the page). 

So, I'm still unclear on the benefit it would bring unless we want that flexibility? 


_(this is all from inspecting types)_ 

<img width="536" alt="Screenshot 2022-07-19 at 08 19 30" src="https://user-images.githubusercontent.com/8166969/179690446-a8220d6e-c67a-455a-a1a8-6e9b6129fb03.png">

<img width="670" alt="Screenshot 2022-07-19 at 08 20 05" src="https://user-images.githubusercontent.com/8166969/179690534-5d7f7f5a-47e2-4277-84b9-32e75131fe7c.png">
<img width="517" alt="Screenshot 2022-07-19 at 08 20 39" src="https://user-images.githubusercontent.com/8166969/179690638-c500ab9c-6d8e-4d95-8043-229a0dd4f88a.png">

**Comment by mrmckeb** [comment]
@adrianbw we were looking at this today. Did you want to progress with this issue?

I also like that it's easier to type function expressions / arrow functions, but I feel we'd need a lot more input before we could make any decision around this.

_For context, this was voted in by the Vercel team around a year ago, but we have many new people today and possibly very different opinions._

**Comment by adrianbw** [comment]
I personally feel strongly that arrow declarations are a better course. But we also have 65535 function declarations already, so I'm leery of the codemod we'd have to run and the number of `eslint-disable`s it would introduce.

**Comment by adrianbw** [comment]
Now that we've added [explicit-function-return-type](https://typescript-eslint.io/rules/explicit-function-return-type/), I feel even more strongly about this. `React.FC` stitches up props and return type into one declaration.

**Comment by mrmckeb** [comment]
We've discussed, and will leave this for now. In future we want to move this to a codemod.
