### ISSUE TITLE
Tabs by default?

### ISSUE THREAD

**Issue by TooTallNate** [vercel/style-guide#31]
Can we start a discussion about using tabs instead of spaces by default?

[Apparently](https://twitter.com/Rich_Harris/status/1541761871585464323), Prettier is considering switching to tabs by default in v3, so if the answer is "we'll default to it when Prettier does" then that's fine with me, but wanted to get the ball rolling if possible.

**Comment by mrmckeb** [comment]
Thanks for raising this @TooTallNate.

> "we'll default to it when Prettier does"

We do sometimes jump ahead of Prettier/etc when we anticipate changes. One example is [trailing commas](https://prettier.io/docs/en/options.html#trailing-commas) where they moved from `none` to `es5`, but we expect they'll eventually move to `all`.

As someone that learnt to program with tabs, I'm not opposed to this at all. Tooling has also improved a lot too.
- You can define your own tab size [in GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference).
- You can define your own tab size in [VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation) (and other editors).

If there's enough support we could make this change earlier, especially as the major "for" argument is accessibility.

I've been following the (heated) discussion here:
https://github.com/prettier/prettier/issues/7475

**Comment by JounQin** [comment]
> You can define your own tab size in [VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation) (and other editors).

It still needs to be defined, manually. And we commonly do not commit `.vscode` settings to git repo, but use a global `settings.json` instead.

It becomes an accessibility issue for those who are not using `tab`. 😀

You should care about the disabled, that's great, but please don't just give up the non-disabled. We deserve accessibility at the same time.

**Comment by mrmckeb** [comment]
Thanks for your input @JounQin.

We (at Vercel) commit some settings for VSCode, but if we move forward with this change, I would expect it to be a per-user setting.

Otherwise, as you pointed out, it would be an annoyance to some users. Making it a user setting means that _user-a_ can set tab-width to 2-chars, and _user-b_ can set their tab-width to 8-chars, without affecting each other.

**Comment by pvdz** [comment]
I'm opposed

- will destroy git history as it will update all files
- makes searching harder as right now you can grep for a space before your query in certain kinds of searches and after you'd have to grep for a space_or_tab
- makes viewing the code in terminal more annoying since they most commonly default to 4 space tabs

I would argue that the JS world is used to spaces anyways but I guess that's a moot point to make.

**Comment by mrmckeb** [comment]
We'll close this off for now and wait for Prettier to make a decision.
